name: Run News Scraper

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Check and remove existing chromedriver
        run: |
          ls -l /usr/bin/chromedriver || echo "No chromedriver found"
          sudo rm -f /usr/bin/chromedriver
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip chromium-browser chromium-chromedriver
          pip install --no-cache-dir -r requirements.txt
      - name: Verify selenium installation
        run: |
          python -c "import selenium; print(selenium.__version__)"
      - name: Run scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          python scraper.py
