name: Run News Scraper

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
      - name: Verify dependencies
        run: |
          python -c "import selenium; print('Selenium version:', selenium.__version__)"
          python -c "import langdetect; print('Langdetect installed')"
          python -c "import dateutil.parser; print('Dateutil.parser installed')"
      - name: Run scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          python scraper.py
