name: Run News Scraper
on:
  schedule:
    - cron: '0 */2 * * *'  # हर 2 घंटे में ऑटो रन
  workflow_dispatch:       # मैन्युअल रन के लिए

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 transformers firebase-admin googletrans==4.0.0-rc1 torch  # torch add kiya summarizer ke liye if needed
      - name: Run Scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python scraper.py
